---
- name: Enable IP forwarding
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
  loop:
    - name: net.ipv4.ip_forward
      value: 1
    - name: net.ipv4.conf.default.rp_filter
      value: 0
    - name: net.ipv4.conf.default.accept_source_route
      value: 0

- name: Install IPSec
  yum:
    name: libreswan

- name: Configure IPSec
  template:
    src: ipsec.conf.j2
    dest: "/etc/ipsec.d/{{ item.name }}.conf"
  loop: "{{ vpns }}"

- name: Configure IPSec secrets
  template:
    src: ipsec.secrets.j2
    dest: "/etc/ipsec.d/{{ item.name }}.secrets"
    mode: 0600
  loop: "{{ vpns }}"
