---
- name: Set time zone
  timezone:
    name: "{{ time_zone }}"
  when: time_zone is defined

- name: Install chronyd #Amazon Linux alternative to ntpdate
  yum:
    name: chrony

# - name: Synchronize clock 
#   command: ntpdate 0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org 3.pool.ntp.org
