---
# TODO: Remove python3.6 after a successful provision.
# - name: Remove Python 3.6
#   yum:
#     name: python3
#     state: absent

# - name: Install package for CentOS SCL repository
#   yum:
#     name:
#       - centos-release-scl
#       # Required by the Ansbile pip module.
#       - python3-setuptools

# - name: Install Python 3.8
#   yum:
#     name:
#       - rh-python38-python
#       - rh-python38-python-devel
#       # Workaround https://github.com/ansible/ansible/issues/47361
#       # Python setuptools is required to run the pip Ansible task.
#       - rh-python38-python-setuptools

- name: Install python tools
  ansible.builtin.dnf:
    name: python3-setuptools