---
- name: Set up RabbitMQ repo
  copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
    mode: 0644

- name: Add repository
  ansible.builtin.command: yum update -y

- name: Install OpenSSL 1.1
  yum:
    name: https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/compat-openssl11-1.1.1k-3.el9.x86_64.rpm
    stage: present
    
# - name: Install erlang
#   yum:
#     name: https://github.com/rabbitmq/erlang-rpm/releases/download/v25.1.1/erlang-25.1.1-1.el9.x86_64.rpm
#     stage: present

- name: Install RabbitMQ
  yum:
    name: rabbitmq-server

- name: Copy rabbitmq-env.conf
  copy:
    src: rabbitmq-env.conf
    dest: /etc/rabbitmq/
    mode: 0644
  register: rabbit_env

- name: Create rabbitmq-server systemd path
  file:
    path: /etc/systemd/system/rabbitmq-server.service.d
    state: directory

- name: Copy rabbitmq-server systemd override.conf
  copy:
    src: roles/common/files/override.conf
    dest: /etc/systemd/system/rabbitmq-server.service.d/override.conf
  register: rabbit_override

- name: Restart RabbitMQ
  systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes
  when: rabbit_env.changed or rabbit_override.changed

- name: Remove guest user from rabbitmq
  rabbitmq_user:
    user: guest
    state: absent
    node: rabbit@localhost
