---
# - name: Install Remi epel package
#   yum:
#     name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"

# - name: Enable Remi PHP RPM repository
#   command: yum-config-manager --enable remi-php80

- name: Install PHP dependencies
  ansible.builtin.dnf:
    name:
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-pgsql"
      - "php{{ php_version }}-soap"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"
      - php-pear
      - composer

- name: Install pecl packages.
  ansible.builtin.command: pecl install {{ item }}
  with_items:
    - zip
    - redis
    - ZendOpcache
  ignore_errors: yes

- name: Download composer
  get_url:
    checksum: 'sha256:https://getcomposer.org/download/latest-stable/composer.phar.sha256sum'
    url: https://getcomposer.org/download/latest-stable/composer.phar
    dest: /usr/bin/composer
    force: yes
    owner: root
    group: root
    mode: 0755

- name:
  template:
    src: erezlife.ini.j2
    dest: /etc/php.d/99-erezlife.ini
  notify: PHP changed
