---
- import_tasks: sudoers.yml

- name: Include AWS variables
  include_vars:
    file: aws_passwords.yml

- name: Copy scripts
  copy:
    src: scripts/
    dest: /usr/local/bin/
    mode: 0755

- name: Create clients group
  group:
    name: clients

- name: Create 'clients' user
  ansible.builtin.user:
    name: clients
    shell: /usr/sbin/nologin
    create_home: yes

- name: Copy sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0600
  notify: Reload sshd

- name: Limit clients upload size to 200 MB
  pam_limits:
    domain: "@clients"
    limit_item: fsize
    limit_type: hard
    value: "204800"  # KB

- import_tasks: s3fs.yml

# - name: Reboot server weekly
#   cron:
#     name: Reboot server weekly
#     job: /usr/sbin/reboot
#     weekday: "2"
#     hour: "22"
#     minute: "18"
