---
- name: Install s3 deps
  yum:
    name: 
      - libxml-devel
      - openssl-devel

- name: Install s3 mount  
  yum:
    name: https://s3.amazonaws.com/mountpoint-s3-release/latest/x86_64/mount-s3.rpm    

- name: S3 mount startup script
  template:
    src: s3-systemd.j2
    dest: /etc/systemd/system/mnt-s3fs.service
    owner: root
    group: root
    mode: 0600

- name: set s3 bucket for sftp
  ansible.builtin.set_fact:
    sftp_bucket: "sandbox-production-erezlife-us-sftp"

- name: Enable and start service
  ansible.builtin.systemd:
    name: mnt-s3fs
    enabled: yes
    state: started
    daemon_reload: yes

# - name: Configure s3fs credentials
#   copy:
#     dest: /etc/passwd-s3fs
#     content: "{{ aws_sftp_access_key_id }}:{{ aws_sftp_secret_access_key }}"
#     mode: "0600"
#   notify: Remount S3FS

# - name: Mount upload buckets
#   mount:
#     path: /home/clients/
#     fstype: fuse.s3fs
#     src: "{{ aws_sftp_bucket }}"
#     opts: _netdev,allow_other,noexec,mp_umask=0022,gid=clients,disable_noobj_cache
#     state: mounted

- name: Enable use of s3fs as home directory
  seboolean:
    name: use_fusefs_home_dirs
    state: yes
    persistent: yes

- name: Make Kernel panic on OOM
  sysctl:
    name: vm.panic_on_oom
    value: '1'

- name: Reboot on kernel panic
  sysctl:
    name: kernel.panic
    # Wait 10 seconds before to reboot, leaving time for helper processes to
    # gather the debugging info (which process caused the OOM, etc.)
    value: '10'
