---
- name: Reload PostgreSQL
  systemd:
    name: "postgresql-{{ postgresql_version }}"
    state: reloaded

- name: Restart PostgreSQL
  systemd:
    name: "postgresql-{{ postgresql_version }}"
    state: restarted
