---
- name: Install Crontab
  yum:
    name: https://rpmfind.net/linux/fedora/linux/releases/38/Everything/x86_64/os/Packages/c/crontabs-1.11-29.20190603git.fc38.noarch.rpm
    disable_gpg_check: true

- name: Setup crontab env
  cron:
    env: yes
    name: MAILTO
    value: "{{ email }}"

# - name: Install crontab job
#   cron:
#     name: Refresh SimpleSAMLphp metadata
#     job: 'curl --silent "https://{{ hostvars[groups[proxy_target][0]].inventory_hostname }}/simplesaml/module.php/cron/cron.php?key={{ saml_cron_key }}&tag=daily"'
#     hour: '12'
#     minute: '30'
