---
- include_vars: roles/web/files/uservoice.yml
- include_vars: roles/web/files/sentry.yml

- name: Gather EC2 metadata facts
  amazon.aws.ec2_metadata_facts:

- name: Set aws region
  ansible.builtin.set_fact:
    aws_region: "{{ ansible_ec2_instance_identity_document_region }}"

- name: Set the proxy target IP
  set_fact:
    proxy_target: "{{ lookup('aws_ssm', 'erezlife-proxy-us-east-1', region=aws_region) }}"
    sftp_target: "{{ lookup('aws_ssm', 'erezlife-sftp-us-east-1', region=aws_region) }}"
    erezadmin_auth_token: "{{ lookup('aws_ssm', '/paramkeys/erezadmin_auth_token', region=aws_region) }}"
    erezadmin_broker_password: "{{ lookup('aws_ssm', '/paramkeys/erezadmin_broker_password', region=aws_region) }}"
    erezlife_github_webhook_secret: "{{ lookup('aws_ssm', '/paramkeys/erezlife_github_webhook_secret', region=aws_region) }}"
    erezadmin_secret_key: "{{ lookup('aws_ssm', '/paramkeys/erezadmin_secret_key', region=aws_region) }}"
    erezadmin_database_password: "{{ lookup('aws_ssm', 'us-production-db-us-east-1', region=aws_region) }}"
    database_host: "{{ lookup('aws_ssm', 'us-production-db-endpoint', region=aws_region) }}"
    aws_backup_bucket: "sandbox-production-erezlife-us-backups"
    aws_sftp_bucket: "sandbox-production-erezlife-ca-sftp"
    aws_upload_bucket: "sandbox-production-erezlife-us-upload"
    aws_tmp_bucket: "sandbox-production-erezlife-ca-tmp"
    aws_lambda_namespace: "sandbox-erezlife"
    aws_log_group: "/sandbox-us-erezlife"

- name: Make SSH connections non-interactive
  copy:
    src: erezadmin_ssh_config
    dest: ~erezadmin/.ssh/config
    mode: 0600
    owner: erezadmin
    group: erezadmin

- name: Install AWS CLI configuration
  become_user: erezadmin
  template:
    src: aws_config.j2
    dest: ~/.aws/config
    mode: 0600

- name: Create Composer directory
  become_user: erezadmin
  file:
    path: ~/.composer
    state: directory

- name: Install cachetool
  become_user: erezadmin
  composer:
    command: require
    arguments: gordalina/cachetool --update-with-all-dependencies
    global_command: yes

- name: Set cron SELinux context
  sefcontext:
    target: /var/spool/cron/erezadmin
    setype: user_cron_spool_t

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
    owner: erezadmin
    group: erezadmin
  loop:
    - /opt/erezadmin
    - /opt/erezadmin/src
    - /opt/erezadmin/venv

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
    owner: erezadmin
    group: erezadmin
    mode: 0700
  loop:
    - /opt/erezadmin/tmp
    - /var/log/erezadmin

- name: Update erezadmin.json
  template:
    src: erezadmin.json.j2
    dest: /etc/erezadmin.json
    owner: erezadmin
    group: erezadmin
    mode: 0640
  notify: Restart erezadmin

- name: Configure allowed users
  copy:
    dest: /etc/erezadmin-users.json
    content: "{{ erezlife_users | to_nice_json(ensure_ascii=False) }}"
    mode: 0640
    owner: erezadmin
    group: erezlife

- name: Copy systemd unit files
  copy:
    src: erezadmin-celery.service
    dest: /etc/systemd/system/
  notify: Reload systemd

- name: Enable erezadmin-celery
  systemd:
    name: erezadmin-celery
    enabled: yes
