---
- name: Lookup {{ item.name }} in AWS SSM Parameter Store
  set_fact:
    ssm_{{item.name}}: "{{ lookup('aws_ssm', item.name) }}"
  ignore_errors: True

- name: Set password length
  ansible.builtin.set_fact:
    password_command: "/dev/null length={{item.size}} chars=ascii_letters,digits"

- name: Generate random password if not found in AWS SSM
  ansible.builtin.set_fact:
    password: "{{ lookup('password', password_command) }}"
  when: ssm_{{item.name}} is failed

- name: Store new password in AWS SSM Parameter Store
  community.aws.aws_ssm:
    name: "/paramkeys/{{ item.name }}"
    value: "{{ password }}"
    type: "SecureString"
    state: present
  when: ssm_{{item.name}} is failed