---
- include_tasks: ssh_keyscan.yml
  loop:
    - "{{ lookup('aws_ssm', 'erezlife-proxy-us-east-1', region=aws_region) }}"
    - "{{ lookup('aws_ssm', 'erezlife-sftp-us-east-1', region=aws_region) }}"
  loop_control:
    loop_var: host

# NOTE: slurp base64 encodes the contents of the file it reads in,
#       so pipe it through b64decode when using the data.
- name: Store public key for erezadmin (from web)
  become_user: erezadmin
  slurp:
    src: ~/.ssh/id_rsa.pub
  register: result

- name: Set erezadmin key fact
  set_fact:
    erezadmin_key: "{{ result.content|b64decode }}"
