---
- name: Install Docker
  yum:
    name:
      - docker
      - containerd

- name: Enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Install Python Docker bindings (for Ansible)
  ansible.builtin.command: pip3 install docker
