---
- hosts: localhost
  connection: local

  pre_tasks:
    - shell: python3 scripts/get-credentials -c scripts/s3_config.json -b erezlife-credentials
    - shell: dnf install python3-pip -y
    - shell: pip install boto3    

  roles:
    - role: erezadmin
      erezadmin_allow_ssh_from_web: yes
    - sftp