---
- name: Install base packages
  yum:
    name:
#      - centos-release-scl  # Clang and LLVM toolsets.
      - https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

- name: Install PostgreSQL
  yum:
    name:
      - "postgresql{{ postgresql_version }}"
      - "postgresql{{ postgresql_version }}-devel"

- import_tasks: server.yml
  when: postgresql_server

- name: Create links for current PostgreSQL version
  file:
    src:  "/usr/pgsql-{{ postgresql_version }}"
    dest:  /usr/pgsql
    state: link
