---
- name: Install uWSGI libraries
  ansible.builtin.yum:
    name:
      - '@Development Tools'
      - python3-devel
      - python3-pip
      - libcap-devel
      - libuuid-devel
      - openssl-devel
      # Used for routing support
      - pcre-devel
      # Using specific version of uWSGI that's compatible with AL2023
      - https://rpmfind.net/linux/fedora/linux/releases/37/Everything/x86_64/os/Packages/u/uwsgi-2.0.20-9.fc37.x86_64.rpm
    disable_gpg_check: true

- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/unbit/uwsgi.git'
    dest: /usr/src/uwsgi
    version: '2.0.20'

- name: Compile uWSGI Python plugin
  command: "sh -c 'PYTHON=python3 uwsgi --build-plugin plugins/python core'"
  args:
    chdir: "/usr/src/uwsgi/"

- name: Create uWSGI lib directory
  file:
    path: /usr/lib64/uwsgi
    state: directory
    mode: 0755

- name: Rename uWSGI Python plugin
  copy:
    remote_src: yes
    src: "/usr/src/uwsgi/python_plugin.so"
    dest: "/usr/lib64/uwsgi/python_plugin.so"

- name: Create uWSGI runtime variable data directory
  command: systemd-tmpfiles --create