---
- name: Install uWSGI libraries
  yum:
    name:
      - '@Development Tools'
      - python3-devel
      - python3-pip
      - libcap-devel
      - libuuid-devel
      - openssl-devel
      # Used for routing support
      - pcre-devel

- name: Install uWSGI
  yum:
    name: https://rpmfind.net/linux/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/u/uwsgi-2.0.24-1.fc40.x86_64.rpm
    state: present      
  notify: Restart uWSGI


# - name: Define uWSGI facts to compile Python plugin (1/2)
#   set_fact:
#     uwsgi_python_version: 3.9
#     uwsgi_version: "{{ uwsgi_version_cmd.stdout }}"

# - name: Define uWSGI facts to compile Python plugin (2/2)
#   set_fact:
#     uwsgi_plugin_python_path: "/usr/src/uwsgi/{{ uwsgi_version }}/python{{ uwsgi_python_version }}_plugin_uwsgi{{ uwsgi_version }}.so"

# - name: Compile uWSGI Python plugin
#   command: "
#     scl enable rh-python38 --
#     sh -c 'PYTHON=python{{ uwsgi_python_version }} uwsgi --build-plugin plugins/python core'
#     "
#   args:
#     chdir: "/usr/src/uwsgi/{{ uwsgi_version }}/"
#     # File is created by the next task. Skip task when the target exists.
#     creates: "{{ uwsgi_plugin_python_path }}"

# - name: Rename uWSGI Python plugin
#   copy:
#     remote_src: yes
#     src: "/usr/src/uwsgi/{{ uwsgi_version }}/python_plugin.so"
#     dest: "{{ uwsgi_plugin_python_path }}"

# - name: Create uWSGI lib directory
#   file:
#     path: /usr/lib64/uwsgi
#     state: directory
#     mode: 0755

# - name: Make uWSGI python plugin available
#   file:
#     path: /usr/lib64/uwsgi/python_plugin.so
#     src: "{{ uwsgi_plugin_python_path }}"
#     state: link

# - name: Create uWSGI runtime variable data directory
#   command: systemd-tmpfiles --create
